#ifndef __CONFIG_H
#define __CONFIG_H

#define THERMO_SETTING_DISPLAY           0
#define THERMO_CONTROLLER_DISPLAY        1
#define THERMO_CONTROLLER_RAW_TEMP       2
#define THERMO_CONTROLLER_MODE           3
#define THERMO_CONTROLLER_USER_TEMP      4
#define THERMO_CONTROLLER_TARGET_TEMP    5
#define THERMO_CONTROLLER_CURRENT_TEMP   6


#define DEBUG_DISPLAY THERMO_CONTROLLER_CURRENT_TEMP

#endif

